name: Compilar e Lancar GeMidi

on:
  push:
    tags:
      - 'v*' # Dispara quando você cria uma tag (ex: v1.0, v1.1)
  workflow_dispatch: # Permite rodar manualmente na aba Actions

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Baixar o codigo do repositorio
      uses: actions/checkout@v4

    - name: Compilar o executavel com GCC
      run: gcc gemidi.c -o gemidi.exe -lwinmm

    - name: Criar Release e disponibilizar o download
      uses: softprops/action-gh-release@v2
      with:
        files: gemidi.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
